env:
  TERM: alacritty
  COLORTERM: truecolor

window:
  title: Alacritty-Git

  decorations_theme_variant: Full
  startup_mode: Windowed
  dynamic_title: true
  opacity: 0.75

  padding:
    x: 2
    y: 4

  dynamic_padding: true

  class:
    instance: Alacritty
    general: terminal_emulator
    gtk_theme_variant: dark

shell:
  program: /usr/bin/fish
  args:
    - --login
    - --interactive

working_directory: None
live_config_reload: true
log_level: Debug
tabspaces: 4

scrolling:
  history: 10000
  multiplier: 3
  auto_scroll: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

  hints:

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: F12, mods: Control, action: ToggleFullscreen }

cursor:
  blink_interval: 500
  blink_timeout: 10
  unfocused_hollow: true
  style:
    shape: Block
    blinking: On

font:
  size: 13.0
  normal:
    family: TerminessTTF Nerd Font Mono
    style: Medium

  bold:
    family: CodeNewRoman Nerd Font Mono
    style: Bold

  italic:
    family: CodeNewRoman Nerd Font Mono
    style: Italic

  bold_italic:
    family: CaskaydiaCove Nerd Font
    style: SemiBold Italic
    size: 14.0

  offset:
    x: 1
    y: 1

  glyph_offset:
    x: 2
    y: 2

  builtin_box_drawing: false

draw_bold_text_with_bright_colors: true

#######################################
##      START OF COLOR SCHEMES       ##
#######################################
schemes:
  ### Doom One ###
  DoomOne: &DoomOne
    primary:
      background: '#282c34'
      foreground: '#bbc2cf'
    cursor:
      text: CellBackground
      cursor: '#528bff'
    selection:
      text: CellForeground
      background: '#3e4451'
    normal:
      black:   '#1c1f24'
      red:     '#ff6c6b'
      green:   '#98be65'
      yellow:  '#da8548'
      blue:    '#51afef'
      magenta: '#c678dd'
      cyan:    '#5699af'
      white:   '#202328'
    bright:
      black:   '#5b6268'
      red:     '#da8548'
      green:   '#4db5bd'
      yellow:  '#ecbe7b'
      blue:    '#3071db'   # This is 2257a0 in Doom Emacs but I lightened it.
      magenta: '#a9a1e1'
      cyan:    '#46d9ff'
      white:   '#dfdfdf'

  ### ISOTOPE DARK ###
  IsotopeDark: &IsotopeDark
    primary:
      background: '#282c34'
      foreground: '#bbc2cf'
    cursor:
      text: CellBackground
      cursor: '#528bff'
    selection:
      text: CellForeground
      background: '#3e4451'
    normal:
      black: "#000000"
      red: "#ff0000"
      green: "#33ff00"
      yellow: "#ff0099"
      blue: "#0066ff"
      magenta: "#cc00ff"
      cyan: "#00ffff"
      white: "#d0d0d0"
    bright:
      black: "#808080"
      red: "#ff0000"
      green: "#33ff00"
      yellow: "#ff0099"
      blue: "#0066ff"
      magenta: "#cc00ff"
      cyan: "#00ffff"
      white: "#ffffff"

  Taerminal: &Taerminal
    primary:
      background: '#26282a'
      foreground: '#f0f0f0'
      cursor:
        background: '#f0f0f0'
        foreground: '#26282a'
    # Normal colors
    normal:
      black:   '#26282a'
      red:     '#ff8878'
      green:   '#b4fb73'
      yellow:  '#fffcb7'
      blue:    '#8bbce5'
      magenta: '#ffb2fe'
      cyan:    '#a2e1f8'
      white:   '#f1f1f1'
    # Bright colors
    bright:
      black:   '#6f6f6f'
      red:     '#fe978b'
      green:   '#d6fcba'
      yellow:  '#fffed5'
      blue:    '#c2e3ff'
      magenta: '#ffc6ff'
      cyan:    '#c0e9f8'
      white:   '#ff00ff'

  ### SWEETIFIED ###
  Sweetified: &Sweetified
    primary:
      background: '0x0a1124'
      foreground: '0xeec49a'
    cursor:
      text: '0xEB3247'
      cursor: '0xF35645'
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    normal:
      black: '0x0a1124'
      red: '0x5F4149'
      green: '0xEB3247'
      yellow: '0xBC4349'
      blue: '0xF35645'
      magenta: '0xF6A73B'
      cyan: '0xFAD32F'
      white: '0xeec49a'
    bright:
      black: '0xa6896b'
      red: '0x5F4149'
      green: '0xEB3247'
      yellow: '0xBC4349'
      blue: '0xF35645'
      magenta: '0xF6A73B'
      cyan: '0xFAD32F'
      white: '0xeec49a'

  ### Dracula ###
  Dracula: &Dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: '#44475a'
        background: '#50fa7b'
      focused_match:
        foreground: '#44475a'
        background: '#ffb86c'
      bar:
        background: '#282a36'
        foreground: '#f8f8f2'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '#44475a'
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#bd93f9'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'
    bright:
      black:   '#4d4d4d'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'
      white:   '#e6e6e6'
    dim:
      black:   '#14151b'
      red:     '#ff2222'
      green:   '#1ef956'
      yellow:  '#ebf85b'
      blue:    '#4d5b86'
      magenta: '#ff46b0'
      cyan:    '#59dffc'
      white:   '#e6e6d1'

  ### Gruvbox dark ###
  GruvboxDark: &GruvboxDark
    # Default colors
    primary:
      # hard contrast: background = '0x1d2021'
      background: '#282828'
      # soft contrast: background = '0x32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

### Monokai ###
  MonokaiPro: &MonokaiPro
    # Default colors
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'

    # Normal colors
    normal:
      black:   '#403E41'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

    # Bright colors
    bright:
      black:   '#727072'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

  ### Nord ###
  Nord: &Nord
    # Default colors
    primary:
      background: '#2E3440'
      foreground: '#D8DEE9'

    # Normal colors
    normal:
      black:   '#3B4252'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#88C0D0'
      white:   '#E5E9F0'

    # Bright colors
    bright:
      black:   '#4C566A'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#8FBCBB'
      white:   '#ECEFF4'

  ### Oceanic Next ###
  OceanicNext: &OceanicNext
    # Default colors
    primary:
      background: '#1b2b34'
      foreground: '#d8dee9'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#1b2b34'
      cursor: '#ff00ff'

    # Normal colors
    normal:
      black:   '#343d46'
      red:     '#EC5f67'
      green:   '#99C794'
      yellow:  '#FAC863'
      blue:    '#6699cc'
      magenta: '#c594c5'
      cyan:    '#5fb3b3'
      white:   '#d8dee9'

    # Bright colors
    bright:
      black:   '#343d46'
      red:     '#EC5f67'
      green:   '#99C794'
      yellow:  '#FAC863'
      blue:    '#6699cc'
      magenta: '#c594c5'
      cyan:    '#5fb3b3'
      white:   '#d8dee9'

  Kitty: &Kitty
  # Default colors
    primary:
      background: '#000000'
      foreground: '#dddddd'

    # Normal colors
    normal:
      black:   '#000000'
      red:     '#cc0403'
      green:   '#19cb00'
      yellow:  '#cecb00'
      blue:    '#0d73cc'
      magenta: '#cb1ed1'
      cyan:    '#0dcdcd'
      white:   '#dddddd'

  # Bright colors
    bright:
      black:   '#767676'
      red:     '#f2201f'
      green:   '#23fd00'
      yellow:  '#fffd00'
      blue:    '#1a8fff'
      magenta: '#fd28ff'
      cyan:    '#14ffff'
      white:   '#ff00ff'

  ### Palenight ###
  Palenight: &Palenight
    # Default colors
    primary:
      background: '#292d3e'
      foreground: '#d0d0d0'

    # Normal colors
    normal:
      black:   '#292d3e'
      red:     '#f07178'
      green:   '#c3e88d'
      yellow:  '#ffcb6b'
      blue:    '#82aaff'
      magenta: '#c792ea'
      cyan:    '#89ddff'
      white:   '#d0d0d0'

    # Bright colors
    bright:
      black:   '#434758'
      red:     '#ff8b92'
      green:   '#ddffa7'
      yellow:  '#ffe585'
      blue:    '#9cc4ff'
      magenta: '#e1acff'
      cyan:    '#a3f7ff'
      white:   '#ff00ff'

  ### Solarized Dark ###
  SolarizedDark: &SolarizedDark
    # Default colors
    primary:
      background: '#002b36' # base03
      foreground: '#839496' # base0

    # Cursor colors
    cursor:
      text:   '#002b36' # base03
      cursor: '#839496' # base0

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  ### Solarized Light ###
  SolarizedLight: &SolarizedLight
    # Default colors
    primary:
      background: '#fdf6e3' # base3
      foreground: '#657b83' # base00

    # Cursor colors
    cursor:
      text:   '#fdf6e3' # base3
      cursor: '#657b83' # base00

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  ### Tomorrow Night ###
  TomorrowNight: &TomorrowNight
     # Default colors
    primary:
      background: '#1d1f21'
      foreground: '#c5c8c6'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#1d1f21'
      cursor: '#ff00ff'

    # Normal colors
    normal:
      black:   '#1d1f21'
      red:     '#cc6666'
      green:   '#b5bd68'
      yellow:  '#e6c547'
      blue:    '#81a2be'
      magenta: '#b294bb'
      cyan:    '#70c0ba'
      white:   '#373b41'

    # Bright colors
    bright:
      black:   '#666666'
      red:     '#ff3334'
      green:   '#9ec400'
      yellow:  '#f0c674'
      blue:    '#81a2be'
      magenta: '#b77ee0'
      cyan:    '#54ced6'
      white:   '#282a2e'
  
colors: *IsotopeDark

visual_bell:
  animation: EaseOutCubic
  duration: 150
  color: '#70c0ba'

alt_send_esc: true