#!/usr/bin/env bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.
export LESS='-F -i -J -M -R -W -x4 -X -z-4'
export EDITOR='/usr/bin/micro'
export VISUAL='/mnt/c/Users/brand/AppData/Local/Programs/Microsoft VS Code/bin'
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
# umask 077
WSL_IPV4="$(hostname -I | awk '{print $1}' | awk '{printf $0}')"
DISPLAY="$(ip route|awk '/^default/{print $3}'):0"

if [[ -n "${WSL_IPV4}" ]]; then
    export WSL_IPV4
fi

if [[ -n "${DISPLAY}" ]]; then
    export DISPLAY
fi


export LESS='-F -i -J -M -R -W -x4 -X -z-4'
# export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_CONFIG_DIRS="/etc/xdg:$XDG_CONFIG_HOME"
# export NVM_DIR="$HOME/.nvm"
# if running bash
if [ -n "$BASH_VERSION" ]; then
  # include .bashrc if it exists
  if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
  fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ]; then
  PATH="$HOME/.bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
  PATH="$HOME/.local/bin:$PATH"
fi

export PATH="$PATH:/mnt/c/Windows/System32:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1/bin:/mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1/libnvvp:/mnt/c/Program Files/usbipd-win:/mnt/c/Users/brand/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Users/brand/AppData/Local/Programs/VSCodium Insiders/bin:/mnt/c/Program Files/dotnet:/mnt/c/Program Files/VcXsrv:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit"
