#!/usr/bin/env zsh

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
umask 022
# ensure PATH entries remain unique after shell reload
typeset -U PATH FPATH CDPATH MANPATH path fpath cdpath manpath

if command -v keychain >/dev/null 2>&1; then
  # eval "$(keychain -k all --quiet)"
  ## /etc/ssh/ssh_host_ed25519_key /etc/ssh/ssh_host_ecdsa_key /etc/ssh/ssh_host_rsa_key
  # eval "$(keychain -k mine)"
  if [[ "$(systemctl is-system-running)" =~ "running" ]]; then
    # echo "systemd is running..."
    # print -P "$(systemctl is-system-running)"
    eval "$(keychain --systemd --nogui --gpg2 --inherit any --dir "$HOME/.config/keychain" --absolute --eval id_ed25519_gh --quiet)"
  else
    # echo "systemd not running..."
    # print -P "$(systemctl is-system-running)"
    eval "$(keychain --nogui --gpg2 --inherit any --dir "$HOME/.config/keychain" --absolute --eval id_ed25519_gh --quiet)"
  fi
fi

export WSL_IPV4="$(hostname -I | awk '{print $1}' | awk '{printf $0}')"
[ -n "$WSL_IPV4" ] && export WSL_IPV4

DISPLAY="$(ip route | awk '/^default/{print $3}'):0"
[ -n "$DISPLAY" ] && export DISPLAY

PNPM_HOME="$HOME/.local/share/pnpm"
# pnpm
case ":$path:" in
*":$PNPM_HOME:"*) ;;
*) path=($PNPM_HOME $path) ;;
esac

NODE_PATH="$PNPM_HOME/nodejs"
export PNPM_HOME NODE_PATH
# pnpm end
