github.com:
    users:
        bleek42:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: bleek42
