PURE_GIT_UP_ARROW='↑'
PURE_GIT_DOWN_ARROW='↓'
PURE_PROMPT_SYMBOL='󰘧'
PURE_PROMPT_VICMD_SYMBOL='ᐸ'

zstyle ':prompt:pure:user' color '045'
zstyle ':prompt:pure:host' color '118'
zstyle ':prompt:pure:path' color '105'
zstyle ':prompt:pure:prompt:success' color '049'
zstyle ':prompt:pure:git:action' color '010'
zstyle ':prompt:pure:git:branch' color '012'
zstyle ':prompt:pure:git:dirty' color '009'
