#!/usr/bin/env zsh

TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S\ncpu\t%P'
export LESS='-R -F -i -J -M -W -x4 -z4'
export PAGER='/usr/bin/less'
export EDITOR='/usr/bin/nvim'
export VISUAL='/mnt/c/Users/brand/AppData/Local/Programs/Microsoft VS Code/bin/code.exe'
export LS_COLORS="$LS_COLORS:ow=30;44:" # fix ls color for folders with 777 permission
export PULSE_SERVER="127.0.0.1"
export LS_COLORS="${LS_COLORS}:ow=30;44:" # fix ls color for folders with 777 permissions
export BROWSER='powershell.exe -command start'


export MANPAGER=$'/bin/sh -c \'col -b | batcat -n -p -l man\''
export MANROFFOPT='-c'

# export NODE_PRESERVE_SYMLINKS=1
# export FD_FIND='fdfind --hidden --no-ignore --exclude .git --follow --color always'
# LESS_TERMCAP_md="$(tput setaf 136)"
# [ -e "$LESS_TERMCAP_md" ] && export LESS_TERMCAP_md
# TREE_CMD="$(tree -aC -I '.git' --dirsfirst "$@" | batcat --plain)"
# [ -e "$TREE_CMD" ] && alias tree="${TREE_CMD}"
# LESS_TERMCAP_md="$(tput setaf 136)"
# [ -e "$LESS_TERMCAP_md" ] && export LESS_TERMCAP_md
# TREE_CMD="$(tree -aC -I '.git' --dirsfirst "$@" | batcat --plain)"
